### ISSUE TITLE
bug 日付を選択するとエラー発生

### ISSUE THREAD

**Issue by Joma-kun** [Joma-kun/BimiNikki#9]
ERROR
Cannot read properties of undefined (reading 'value')
TypeError: Cannot read properties of undefined (reading 'value')
    at onChange (http://localhost:3000/main.598b7949cdfb2f897b64.hot-update.js:153:43)
    at http://localhost:3000/static/js/bundle.js:28431:29
    at http://localhost:3000/static/js/bundle.js:22319:19
    at http://localhost:3000/static/js/bundle.js:28403:25
    at http://localhost:3000/static/js/bundle.js:22319:19
    at http://localhost:3000/static/js/bundle.js:23662:14
    at http://localhost:3000/static/js/bundle.js:22319:19
    at http://localhost:3000/static/js/bundle.js:24310:5
    at http://localhost:3000/static/js/bundle.js:22319:19
    at handleClick (http://localhost:3000/static/js/bundle.js:26297:7)
ERROR
Cannot read properties of undefined (reading 'value')
TypeError: Cannot read properties of undefined (reading 'value')
    at onChange (http://localhost:3000/main.598b7949cdfb2f897b64.hot-update.js:153:43)
    at http://localhost:3000/static/js/bundle.js:28431:29
    at http://localhost:3000/static/js/bundle.js:22319:19
    at http://localhost:3000/static/js/bundle.js:28403:25
    at http://localhost:3000/static/js/bundle.js:22319:19
    at http://localhost:3000/static/js/bundle.js:23662:14
    at http://localhost:3000/static/js/bundle.js:22319:19
    at http://localhost:3000/static/js/bundle.js:24310:5
    at http://localhost:3000/static/js/bundle.js:22319:19
    at handleClick (http://localhost:3000/static/js/bundle.js:26297:7)

**Comment by Joma-kun** [comment]
`e`オブジェクトが存在しないためにエラーが発生していた模様
`e.target.value` を使用するのではなく，オブジェクトから直接日付情報を取得
```
onChange={(e) => setValue(e)}
```
